apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-streamer-deployment   # This is your EKS_DEPLOYMENT name
  namespace: default             # Change if you use a different namespace (EKS_NAMESPACE)
  labels:
    app: ai-streamer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-streamer
  template:
    metadata:
      labels:
        app: ai-streamer
    spec:
      containers:
        - name: ai-streamer      # This is your CONTAINER_NAME value
          image: 038462756156.dkr.ecr.us-east-1.amazonaws.com/ai-streamer:latest
          ports:
            - containerPort: 5000  # Adjust if your Flask app listens on a different port
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-streamer-service
  namespace: default
spec:
  type: LoadBalancer   # Change to NodePort or ClusterIP if preferred
  selector:
    app: ai-streamer
  ports:
    - protocol: TCP
      port: 80           # The external port (e.g., for an Ingress or LB)
      targetPort: 5000   # The port on your container
