# ----------------- Frontend Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-monitor-frontend
  labels:
    app: stream-monitor-frontend
    tier: frontend
  annotations:
    kubernetes.io/description: "Frontend web interface for Stream Monitor application"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: stream-monitor-frontend
  template:
    metadata:
      labels:
        app: stream-monitor-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: 038462756156.dkr.ecr.us-east-1.amazonaws.com/stream-monitor-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
---
# ----------------- Frontend Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: stream-monitor-frontend
  labels:
    app: stream-monitor-frontend
    tier: frontend
  annotations:
    kubernetes.io/description: "Frontend service for Stream Monitor application"
spec:
  type: LoadBalancer  # Changed from NodePort for better cloud integration
  selector:
    app: stream-monitor-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
# ----------------- Frontend HorizontalPodAutoscaler -----------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stream-monitor-frontend-hpa
  labels:
    app: stream-monitor-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream-monitor-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70