name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      # # Build and push backend Docker image to ECR
      # - name: Build backend Docker image
      #   run: |
      #     docker build -t stream-monitor-backend:latest ./backend
      #     docker tag stream-monitor-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stream-monitor-backend:latest
      # - name: Push backend Docker image
      #   run: |
      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stream-monitor-backend:latest
      
      # Build and push frontend Docker image to ECR
      - name: Build frontend Docker image
        run: |
          docker build -t stream-monitor-frontend:latest ./frontend
          docker tag stream-monitor-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stream-monitor-frontend:latest
      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/stream-monitor-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Configure AWS credentials again for deployment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Update kubeconfig to interact with your EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name stream-monitor

      # Deploy the Kubernetes manifests to EKS using an inline heredoc
      - name: Deploy to EKS
        run: |
          https://raw.githubusercontent.com/kashimkyari/AI_LiveStream_Monioring_Tool/refs/heads/main/k8s/deploy-frntend.yml