name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Wait for the EKS cluster to be active
      - name: Wait for EKS cluster to be active
        run: |
          aws eks wait cluster-active --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_REGION }}

      # 4. Update kubeconfig so kubectl can communicate with your EKS cluster
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }} --region ${{ secrets.AWS_REGION }}

      # 5. Apply the Kubernetes manifest to create/update your deployment
      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f eks-deployment.yaml --namespace ${{ secrets.EKS_NAMESPACE }}

      # 6. Optionally, wait for the rollout to complete
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/${{ secrets.EKS_DEPLOYMENT }} --namespace ${{ secrets.EKS_NAMESPACE }}

      # 7. Update the deployment with the latest image from ECR
      - name: Update Kubernetes Deployment Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          echo "Deploying image: $IMAGE_URI"
          echo "Deployment: ${{ secrets.EKS_DEPLOYMENT }}"
          echo "Container: ${{ secrets.CONTAINER_NAME }}"
          echo "Namespace: ${{ secrets.EKS_NAMESPACE }}"
          kubectl set image deployment/${{ secrets.EKS_DEPLOYMENT }} "${{ secrets.CONTAINER_NAME }}=$IMAGE_URI" --namespace ${{ secrets.EKS_NAMESPACE }}
